<a href="https://colab.research.google.com/github/HanRunbing/Tool_boxes/blob/main/dimension_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x = np.array([2,4,5,6,7])
w = np.array([5,6,7,8,8])
x.shape

(5,)

In [ ]:
x * w

array([10, 24, 35, 48, 56])

In [ ]:
x.T * w

array([10, 24, 35, 48, 56])

In [ ]:
x.T 

array([2, 4, 5, 6, 7])

In [ ]:
x = np.array([[2,4,5,6,7],[1,2,5,6,7]])
x.shape

(2, 5)

In [ ]:
x * w

array([[10, 24, 35, 48, 56],
       [ 5, 12, 35, 48, 56]])

In [ ]:
x == x.T

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

In [ ]:
x.T * w

ValueError: ignored

In [ ]:
w = np.array([[1,2],[2,3],[2,5],[7,8],[4,5]])
w.shape

(5, 2)

In [ ]:
x * w

ValueError: ignored

In [ ]:
x.T * w

array([[ 2,  2],
       [ 8,  6],
       [10, 25],
       [42, 48],
       [28, 35]])